### ISSUE TITLE
Initialization order

### ISSUE THREAD

**Issue by AljoschaMeyer** [AljoschaMeyer/chainable-command#1]
Currently, piping to a CommandInstance before the ready event was emitted causes an error. But init is called before this event, so a CommandInstance may output data, before being able to accept it itself. Consequently, chained command must be started in reverse order, but that's not what we want.

Edit: fixed in @65e9a0ceac8e84d493d84db6684d19a5968e6fc5

**Comment by AljoschaMeyer** [comment]
When this is done, the `'ready'` event becomes somewhat pointless, because we can treat the CommandInstance just the same whether it is ready or not. Remove the event?

~~The `start()` method itself might be unnecessary, `init()` can simply be called in the constructor. Any output from `init` and `cleanup` will be buffered in `stdout` and `stderr` and is supplied once piped into another CommandInstance (or the final output).~~

We still need `start`, so we can connect commands before calling init. That way, the `stdout` and `stderr` invocations in `init` can be received in the correct order.

**Comment by AljoschaMeyer** [comment]
Removed the ready event in 45d741a3bd4c40d04fa27984d6537af4daf15ac7.

**Comment by dthree** [comment]
k
