### ISSUE TITLE
Renames and terminology

### ISSUE THREAD

**Issue by AljoschaMeyer** [AljoschaMeyer/chainable-command#4]
I'd like to discuss the rename suggestions in dthree/vorpal#95 and put them into one commit:
- `this.stdout` => `this.log` and `this.stderr` => `this.error`: I agree with these in the context of vorpal, but not for the underlying implementation. On this low level, stdout and stderr reflect more accurately what they do.
- `onInput` => `data`: I like using a stream analogy, so :+1: for this.
- `cleanup` => `end`: Same as above, but: We could rename the `'exit'` event to `'end'`, in which case 'cleanup' should stay 'cleanup'.

On a similiar note to `cleanup` => `end` vs `'exit'` => `'end'` there is also `init` (first lifecycle function) and `start` (instance method of CommandInstance to start the lifecycle) ~~and `'ready'` (event emitted when ready to accept input)~~. Feel free to share any better naming ideas for these three.

---

Vorpal will most likely end up wrapping this module anyways, so it can inject its own terminology where necessary.

**Comment by dthree** [comment]
Okay I'm good! :+1:
